# Generated by Django 3.1.2 on 2020-10-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='avatar',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
